apiVersion: v1
kind: Service
metadata:
  name: eksbench
spec:
  type: LoadBalancer
  selector:
    app: ctmbench
  ports:
    - name: ctmweb
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: ctmagent
      protocol: TCP
      port: 7005
      targetPort: 7005
